package Vista.GUI;

import Modelo.OperacionesFicheros;
import Vista.DTO.Fichero;
import Vista.Logica.LogicaFichero;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Gonzalo
 */
public class JFrameVentanaPrincipal extends javax.swing.JFrame {

    ArrayList<String> extensiones = new ArrayList<>();

    /**
     * Creates new form JFrameVentanaPrincipal
     */
    public JFrameVentanaPrincipal() {
        initComponents();
    }

    public void actualizarInterfazProgreso(String rutaArchivo, int progreso) {
        jLabelNombreFicheroCopiado.setText(rutaArchivo);
        jProgressBarFicherosCopiados.setValue(progreso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelROrigen = new javax.swing.JLabel();
        jLabelRDestino = new javax.swing.JLabel();
        jPanelConfiguracion = new javax.swing.JPanel();
        jLabelConfiguracion = new javax.swing.JLabel();
        jLabelArchivosCopiar = new javax.swing.JLabel();
        jButtonSeleccionar2 = new javax.swing.JButton();
        jLabelDestino = new javax.swing.JLabel();
        jButtonSeleccionar1 = new javax.swing.JButton();
        jLabelTiposArchivo = new javax.swing.JLabel();
        jCheckBoxJPG = new javax.swing.JCheckBox();
        jCheckBoxGIF = new javax.swing.JCheckBox();
        jCheckBoxPNG = new javax.swing.JCheckBox();
        jCheckBoxAVI = new javax.swing.JCheckBox();
        jCheckBoxMP4 = new javax.swing.JCheckBox();
        jCheckBoxMP3 = new javax.swing.JCheckBox();
        jCheckBoxWAV = new javax.swing.JCheckBox();
        jCheckBoxPDF = new javax.swing.JCheckBox();
        jCheckBoxTXT = new javax.swing.JCheckBox();
        jCheckBoxDOC = new javax.swing.JCheckBox();
        jCheckBoxTodos = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabelRutaOrigen = new javax.swing.JLabel();
        jLabelRutaDestino = new javax.swing.JLabel();
        jButtonBackUp = new javax.swing.JButton();
        jButtonEspacioLibre = new javax.swing.JButton();
        jLabelEspacioLibreYDuplicados = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonDuplicados = new javax.swing.JButton();
        jPanelOtrasOpciones = new javax.swing.JPanel();
        jLabelOtrasOpciones = new javax.swing.JLabel();
        jButtonEliminarCopia = new javax.swing.JButton();
        jButtonEliminarDuplicados = new javax.swing.JButton();
        jButtonOrganizarBackUp = new javax.swing.JButton();
        jButtonEliminarCopiaOrdenada = new javax.swing.JButton();
        jButtonArchivosCopiados = new javax.swing.JButton();
        jLabelAvisos = new javax.swing.JLabel();
        jProgressBarFicherosCopiados = new javax.swing.JProgressBar();
        jButtonVerDuplicados = new javax.swing.JButton();
        jLabelNombreFicheroCopiado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelROrigen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelROrigen.setText("Ruta Origen");

        jLabelRDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRDestino.setText("Ruta Destino");

        jPanelConfiguracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelConfiguracion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelConfiguracion.setText("Configuración");

        jLabelArchivosCopiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelArchivosCopiar.setText("Seleccionar ruta de archivos a copiar");

        jButtonSeleccionar2.setText("Seleccionar");
        jButtonSeleccionar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeleccionar2MouseClicked(evt);
            }
        });

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDestino.setText("Seleccionar ruta de destino");

        jButtonSeleccionar1.setText("Seleccionar");
        jButtonSeleccionar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSeleccionar1MouseClicked(evt);
            }
        });

        jLabelTiposArchivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTiposArchivo.setText("Selecciona los archivos a copiar");

        jCheckBoxJPG.setText("jpg");
        jCheckBoxJPG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxJPGMouseClicked(evt);
            }
        });

        jCheckBoxGIF.setText("gif");
        jCheckBoxGIF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxGIFMouseClicked(evt);
            }
        });

        jCheckBoxPNG.setText("png");
        jCheckBoxPNG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxPNGMouseClicked(evt);
            }
        });

        jCheckBoxAVI.setText("avi");
        jCheckBoxAVI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxAVIMouseClicked(evt);
            }
        });

        jCheckBoxMP4.setText("mp4");
        jCheckBoxMP4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMP4MouseClicked(evt);
            }
        });

        jCheckBoxMP3.setText("mp3");
        jCheckBoxMP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMP3MouseClicked(evt);
            }
        });

        jCheckBoxWAV.setText("wav");
        jCheckBoxWAV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxWAVMouseClicked(evt);
            }
        });

        jCheckBoxPDF.setText("pdf");
        jCheckBoxPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxPDFMouseClicked(evt);
            }
        });

        jCheckBoxTXT.setText("txt");
        jCheckBoxTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTXTMouseClicked(evt);
            }
        });

        jCheckBoxDOC.setText("doc");
        jCheckBoxDOC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxDOCMouseClicked(evt);
            }
        });

        jCheckBoxTodos.setText("Todos");
        jCheckBoxTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxTodosMouseClicked(evt);
            }
        });

        jButton1.setText("Información");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfiguracionLayout = new javax.swing.GroupLayout(jPanelConfiguracion);
        jPanelConfiguracion.setLayout(jPanelConfiguracionLayout);
        jPanelConfiguracionLayout.setHorizontalGroup(
            jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxJPG)
                                    .addComponent(jCheckBoxMP3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxPNG)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxGIF))
                                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxWAV)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxPDF)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxAVI)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxMP4))
                                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxTXT)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxDOC))))
                            .addComponent(jCheckBoxTodos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                        .addComponent(jLabelTiposArchivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                        .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jLabelArchivosCopiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSeleccionar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSeleccionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanelConfiguracionLayout.setVerticalGroup(
            jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfiguracion)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArchivosCopiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSeleccionar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeleccionar2)
                    .addComponent(jLabelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTiposArchivo)
                .addGap(13, 13, 13)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxJPG)
                    .addComponent(jCheckBoxPNG)
                    .addComponent(jCheckBoxGIF)
                    .addComponent(jCheckBoxAVI)
                    .addComponent(jCheckBoxMP4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMP3)
                    .addComponent(jCheckBoxWAV)
                    .addComponent(jCheckBoxPDF)
                    .addComponent(jCheckBoxTXT)
                    .addComponent(jCheckBoxDOC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxTodos)
                .addContainerGap())
        );

        jLabelRutaOrigen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRutaOrigen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelRutaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonBackUp.setText("Hacer BackUp");
        jButtonBackUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackUpMouseClicked(evt);
            }
        });

        jButtonEspacioLibre.setText("Espacio libre en disco");
        jButtonEspacioLibre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEspacioLibreMouseClicked(evt);
            }
        });

        jLabelEspacioLibreYDuplicados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 0, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Copia de seguridad de discos");

        jButtonDuplicados.setText("Archivos duplicados");
        jButtonDuplicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDuplicadosMouseClicked(evt);
            }
        });

        jPanelOtrasOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelOtrasOpciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOtrasOpciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOtrasOpciones.setText("Otras Opciones");

        jButtonEliminarCopia.setText("Eliminar Copia");
        jButtonEliminarCopia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarCopiaMouseClicked(evt);
            }
        });

        jButtonEliminarDuplicados.setText("Eliminar Duplicados");
        jButtonEliminarDuplicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarDuplicadosMouseClicked(evt);
            }
        });

        jButtonOrganizarBackUp.setText("Organizar BackUp");
        jButtonOrganizarBackUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOrganizarBackUpMouseClicked(evt);
            }
        });

        jButtonEliminarCopiaOrdenada.setText("Eliminar Copia Ordenada");
        jButtonEliminarCopiaOrdenada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarCopiaOrdenadaMouseClicked(evt);
            }
        });

        jButtonArchivosCopiados.setText("Ver Archivos Copiados");
        jButtonArchivosCopiados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonArchivosCopiadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelOtrasOpcionesLayout = new javax.swing.GroupLayout(jPanelOtrasOpciones);
        jPanelOtrasOpciones.setLayout(jPanelOtrasOpcionesLayout);
        jPanelOtrasOpcionesLayout.setHorizontalGroup(
            jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOtrasOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelOtrasOpcionesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEliminarDuplicados, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButtonEliminarCopia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelOtrasOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonOrganizarBackUp, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarCopiaOrdenada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonArchivosCopiados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOtrasOpcionesLayout.setVerticalGroup(
            jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOtrasOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOtrasOpciones)
                    .addComponent(jButtonArchivosCopiados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarCopia)
                    .addComponent(jButtonOrganizarBackUp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOtrasOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarDuplicados)
                    .addComponent(jButtonEliminarCopiaOrdenada))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelAvisos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAvisos.setText(" ");

        jButtonVerDuplicados.setText("Ver duplicados");
        jButtonVerDuplicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerDuplicadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelROrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(171, 171, 171))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelRDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(167, 167, 167))
                            .addComponent(jLabelRutaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRutaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEspacioLibreYDuplicados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarFicherosCopiados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonDuplicados, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(jButtonBackUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonVerDuplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonEspacioLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelNombreFicheroCopiado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOtrasOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelROrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRutaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRutaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEspacioLibre)
                            .addComponent(jButtonBackUp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDuplicados)
                            .addComponent(jButtonVerDuplicados))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEspacioLibreYDuplicados, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jProgressBarFicherosCopiados, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreFicheroCopiado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOtrasOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeleccionar1MouseClicked
        jLabelAvisos.setText("");
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int result = buscador.showOpenDialog(jLabelRutaOrigen);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fichero = buscador.getSelectedFile();
            jLabelRutaOrigen.setText(fichero.getAbsolutePath());
        } else if (result == JFileChooser.CANCEL_OPTION) {
            jLabelRutaOrigen.setText("No se seleccionó ningún directorio/archivo.");
        }
    }//GEN-LAST:event_jButtonSeleccionar1MouseClicked

    private void jButtonEspacioLibreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEspacioLibreMouseClicked
        jLabelAvisos.setText("");
        if ("".equals(jLabelRutaDestino.getText())) {
            jLabelAvisos.setForeground(Color.red);
            jLabelAvisos.setText("Por favor introduce la ruta del disco (destino) para saber el espacio libre.");
        } else {
            File disco = new File(jLabelRutaDestino.getText());
            long espacio = OperacionesFicheros.espacioLibre(disco);
            jLabelEspacioLibreYDuplicados.setText("Quedan " + espacio + "Gb libres");
        }
    }//GEN-LAST:event_jButtonEspacioLibreMouseClicked

    private void jButtonSeleccionar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSeleccionar2MouseClicked
        jLabelAvisos.setText("");
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = buscador.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fichero = buscador.getSelectedFile();
            jLabelRutaDestino.setText(fichero.getAbsolutePath());
        } else if (result == JFileChooser.CANCEL_OPTION) {
            jLabelRutaDestino.setText("No se seleccionó ningún directorio/archivo.");
        }
    }//GEN-LAST:event_jButtonSeleccionar2MouseClicked

    private void jButtonBackUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackUpMouseClicked
        try {
            jLabelAvisos.setText("");
            if ("".equals(jLabelRutaDestino.getText())) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Por favor introduce las rutas de origen y destino.");
            } else {
                File rutaOrigen = new File(jLabelRutaOrigen.getText());
                File rutaDestino = new File(jLabelRutaDestino.getText() + "\\BackUp");
                ArrayList<File> numFicheros = new ArrayList<>();
                OperacionesFicheros operaciones = new OperacionesFicheros(this);

                numFicheros = OperacionesFicheros.listarFicherosExtension(rutaOrigen, extensiones);
                jProgressBarFicherosCopiados.setMaximum(numFicheros.size());
                Thread queryThread = new Thread() {
                    @Override
                    public void run() {
                        try {
                            operaciones.copiarConFiltro(rutaOrigen, rutaDestino, extensiones, 1);
                            OperacionesFicheros.eliminaCarpetasVacias(rutaDestino);
                        } catch (IOException ex) {
                            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                };
                queryThread.start();
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabelAvisos.setForeground(Color.green);
        jLabelAvisos.setText("Se ha hecho la copia de seguridad.");
    }//GEN-LAST:event_jButtonBackUpMouseClicked

    private void jButtonDuplicadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDuplicadosMouseClicked
        try {
            jLabelAvisos.setText("");
            ArrayList<File> listaDuplicados = new ArrayList<>();
            if ("".equals(jLabelRutaDestino.getText())) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Debes hacer primero el backup para comprobar si hay arcivos duplicados o seleccionar la ruta destino.");
            } else {
                File ruta = new File(jLabelRutaDestino.getText() + File.separator + "BackUp");
                listaDuplicados = OperacionesFicheros.buscarDuplicados(ruta);
                jLabelEspacioLibreYDuplicados.setText("Encontrados " + listaDuplicados.size() + " duplicados");
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDuplicadosMouseClicked

    private void jButtonEliminarCopiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarCopiaMouseClicked
        try {
            jLabelAvisos.setText("");
            if ("".equals(jLabelRutaDestino.getText())) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Por favor introduce la ruta del directorio a eliminar (destino).");
            } else {
                File ruta = new File(jLabelRutaDestino.getText() + File.separator + "BackUp");
                OperacionesFicheros.eliminarCopia(ruta);
                jLabelAvisos.setForeground(Color.green);
                jLabelAvisos.setText("Se ha borrado la copia de seguirad.");
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarCopiaMouseClicked

    private void jButtonOrganizarBackUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOrganizarBackUpMouseClicked
        try {
            jLabelAvisos.setText("");
            if ("".equals(jLabelRutaDestino.getText())) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Debes hacer primero la copia de seguridad.");
            } else {
                File rutaBackUp = new File(jLabelRutaDestino.getText() + File.separator + "BackUp");
                OperacionesFicheros.oredenarBackUp(rutaBackUp, jLabelRutaDestino.getText() + File.separator + "BackUp");
                jLabelAvisos.setForeground(Color.green);
                jLabelAvisos.setText("Se ha ordenado la copia de seguirad en una nueva carpeta.");
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOrganizarBackUpMouseClicked

    private void jCheckBoxTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTodosMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxTodos.isSelected()) {
            jCheckBoxJPG.setSelected(true);
            extensiones.add(jCheckBoxJPG.getText());
            jCheckBoxPNG.setSelected(true);
            extensiones.add(jCheckBoxPNG.getText());
            jCheckBoxGIF.setSelected(true);
            extensiones.add(jCheckBoxGIF.getText());
            jCheckBoxAVI.setSelected(true);
            extensiones.add(jCheckBoxAVI.getText());
            jCheckBoxMP4.setSelected(true);
            extensiones.add(jCheckBoxMP4.getText());
            jCheckBoxMP3.setSelected(true);
            extensiones.add(jCheckBoxMP3.getText());
            jCheckBoxWAV.setSelected(true);
            extensiones.add(jCheckBoxWAV.getText());
            jCheckBoxPDF.setSelected(true);
            extensiones.add(jCheckBoxPDF.getText());
            jCheckBoxTXT.setSelected(true);
            extensiones.add(jCheckBoxTXT.getText());
            jCheckBoxDOC.setSelected(true);
            extensiones.add(jCheckBoxDOC.getText());
        } else if (!jCheckBoxTodos.isSelected()) {
            jCheckBoxJPG.setSelected(false);
            jCheckBoxPNG.setSelected(false);
            jCheckBoxGIF.setSelected(false);
            jCheckBoxAVI.setSelected(false);
            jCheckBoxMP4.setSelected(false);
            jCheckBoxMP3.setSelected(false);
            jCheckBoxWAV.setSelected(false);
            jCheckBoxPDF.setSelected(false);
            jCheckBoxTXT.setSelected(false);
            jCheckBoxDOC.setSelected(false);
            Iterator iterator = extensiones.iterator();
            while (iterator.hasNext()) {
                if (extensiones.contains(iterator.next())) {
                    iterator.remove();
                }
            }
        }
    }//GEN-LAST:event_jCheckBoxTodosMouseClicked

    private void jCheckBoxJPGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxJPGMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxJPG.isSelected()) {
            extensiones.add(jCheckBoxJPG.getText());
        } else {
            if (extensiones.contains(jCheckBoxJPG.getText())) {
                extensiones.remove(jCheckBoxJPG.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxJPGMouseClicked

    private void jCheckBoxPNGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxPNGMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxPNG.isSelected()) {
            extensiones.add(jCheckBoxPNG.getText());
        } else {
            if (extensiones.contains(jCheckBoxPNG.getText())) {
                extensiones.remove(jCheckBoxPNG.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxPNGMouseClicked

    private void jCheckBoxGIFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxGIFMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxGIF.isSelected()) {
            extensiones.add(jCheckBoxGIF.getText());
        } else {
            if (extensiones.contains(jCheckBoxGIF.getText())) {
                extensiones.remove(jCheckBoxGIF.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxGIFMouseClicked

    private void jCheckBoxAVIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAVIMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxAVI.isSelected()) {
            extensiones.add(jCheckBoxAVI.getText());
        } else {
            if (extensiones.contains(jCheckBoxAVI.getText())) {
                extensiones.remove(jCheckBoxAVI.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxAVIMouseClicked

    private void jCheckBoxMP4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMP4MouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxMP4.isSelected()) {
            extensiones.add(jCheckBoxMP4.getText());
        } else {
            if (extensiones.contains(jCheckBoxMP4.getText())) {
                extensiones.remove(jCheckBoxMP4.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxMP4MouseClicked

    private void jCheckBoxMP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMP3MouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxMP3.isSelected()) {
            extensiones.add(jCheckBoxMP3.getText());
        } else {
            if (extensiones.contains(jCheckBoxMP3.getText())) {
                extensiones.remove(jCheckBoxMP3.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxMP3MouseClicked

    private void jCheckBoxWAVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxWAVMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxWAV.isSelected()) {
            extensiones.add(jCheckBoxWAV.getText());
        } else {
            if (extensiones.contains(jCheckBoxWAV.getText())) {
                extensiones.remove(jCheckBoxWAV.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxWAVMouseClicked

    private void jCheckBoxPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxPDFMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxPDF.isSelected()) {
            extensiones.add(jCheckBoxPDF.getText());
        } else {
            if (extensiones.contains(jCheckBoxPDF.getText())) {
                extensiones.remove(jCheckBoxPDF.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxPDFMouseClicked

    private void jCheckBoxTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxTXTMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxTXT.isSelected()) {
            extensiones.add(jCheckBoxTXT.getText());
        } else {
            if (extensiones.contains(jCheckBoxTXT.getText())) {
                extensiones.remove(jCheckBoxTXT.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxTXTMouseClicked

    private void jCheckBoxDOCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxDOCMouseClicked
        jLabelAvisos.setText("");
        if (jCheckBoxDOC.isSelected()) {
            extensiones.add(jCheckBoxDOC.getText());
        } else {
            if (extensiones.contains(jCheckBoxDOC.getText())) {
                extensiones.remove(jCheckBoxDOC.getText());
            }
        }
    }//GEN-LAST:event_jCheckBoxDOCMouseClicked

    private void jButtonEliminarCopiaOrdenadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarCopiaOrdenadaMouseClicked
        try {
            jLabelAvisos.setText("");
            File copiaOrdenada = new File(jLabelRutaDestino.getText() + File.separator + "BackUpOrdenado");
            if (!copiaOrdenada.exists()) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("La copia ordenada no existe o no está hecha, por favor introduce la ruta correcta o haz la copia ordenada.");
            } else {
                OperacionesFicheros.eliminarCopia(copiaOrdenada);
                jLabelAvisos.setForeground(Color.green);
                jLabelAvisos.setText("Se ha borrado la copia de seguirad ordenada.");
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarCopiaOrdenadaMouseClicked

    private void jButtonArchivosCopiadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonArchivosCopiadosMouseClicked
        try {
            jLabelAvisos.setText("");
            File ruta = new File(jLabelRutaDestino.getText() + File.separator + "BackUp");
            if (!ruta.exists()) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Para ver los archivos copiados debes hacer la copia de seguridad primero o seleccionar la ruta destino.");
            } else {
                ArrayList<File> lista = new ArrayList<>();
                lista = OperacionesFicheros.listarFicherosExtension(ruta, extensiones);
                for (File file : lista) {
                    if ((!file.isDirectory()) || (!file.exists())) {
                        int indice = file.getName().indexOf(".");
                        String extension = file.getName().toLowerCase().substring(indice + 1);
                        Fichero f = new Fichero(file.getName(), extension, file.length());
                        LogicaFichero.add(f);
                    }
                }
                TablaFicheros t = new TablaFicheros(this, true);
                t.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonArchivosCopiadosMouseClicked

    private void jButtonEliminarDuplicadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarDuplicadosMouseClicked
        try {
            jLabelAvisos.setText("");
            File ruta = new File(jLabelRutaDestino.getText() + File.separator + "BackUp");
            if (!ruta.exists()) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Para borrar duplicados debes hacer primero copia de seguridad primero o seleccionar la ruta destino.");
            } else {
                OperacionesFicheros.borrarDuplicados(ruta);
                OperacionesFicheros.eliminaCarpetasVacias(ruta);
                jLabelAvisos.setForeground(Color.green);
                jLabelAvisos.setText("Se han borrado los archivos duplicados");
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEliminarDuplicadosMouseClicked

    private void jButtonVerDuplicadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerDuplicadosMouseClicked
        try {
            jLabelAvisos.setText("");
            File ruta = new File(jLabelRutaDestino.getText() + File.separator + "BackUp");
            if (!ruta.exists()) {
                jLabelAvisos.setForeground(Color.red);
                jLabelAvisos.setText("Para ver los archivos duplicados debes hacer la copia de seguridad primero o seleccionar la ruta destino.");
            } else {
                ArrayList<File> listaDuplicados = new ArrayList<>();
                listaDuplicados = OperacionesFicheros.buscarDuplicados(ruta);
                for (File file : listaDuplicados) {
                    int indice = file.getName().indexOf(".");
                    String extension = file.getName().toLowerCase().substring(indice + 1);
                    Fichero f = new Fichero(file.getName(), extension, file.length());
                    LogicaFichero.add(f);
                }
                TablaFicherosDuplicados t = new TablaFicherosDuplicados(this, true);
                t.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVerDuplicadosMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jLabelAvisos.setText("");
        PantallaInformación pantallaInformacion = new PantallaInformación(this, true);
        pantallaInformacion.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonArchivosCopiados;
    private javax.swing.JButton jButtonBackUp;
    private javax.swing.JButton jButtonDuplicados;
    private javax.swing.JButton jButtonEliminarCopia;
    private javax.swing.JButton jButtonEliminarCopiaOrdenada;
    private javax.swing.JButton jButtonEliminarDuplicados;
    private javax.swing.JButton jButtonEspacioLibre;
    private javax.swing.JButton jButtonOrganizarBackUp;
    private javax.swing.JButton jButtonSeleccionar1;
    private javax.swing.JButton jButtonSeleccionar2;
    private javax.swing.JButton jButtonVerDuplicados;
    private javax.swing.JCheckBox jCheckBoxAVI;
    private javax.swing.JCheckBox jCheckBoxDOC;
    private javax.swing.JCheckBox jCheckBoxGIF;
    private javax.swing.JCheckBox jCheckBoxJPG;
    private javax.swing.JCheckBox jCheckBoxMP3;
    private javax.swing.JCheckBox jCheckBoxMP4;
    private javax.swing.JCheckBox jCheckBoxPDF;
    private javax.swing.JCheckBox jCheckBoxPNG;
    private javax.swing.JCheckBox jCheckBoxTXT;
    private javax.swing.JCheckBox jCheckBoxTodos;
    private javax.swing.JCheckBox jCheckBoxWAV;
    private javax.swing.JLabel jLabelArchivosCopiar;
    private javax.swing.JLabel jLabelAvisos;
    private javax.swing.JLabel jLabelConfiguracion;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelEspacioLibreYDuplicados;
    private javax.swing.JLabel jLabelNombreFicheroCopiado;
    private javax.swing.JLabel jLabelOtrasOpciones;
    private javax.swing.JLabel jLabelRDestino;
    private javax.swing.JLabel jLabelROrigen;
    private javax.swing.JLabel jLabelRutaDestino;
    private javax.swing.JLabel jLabelRutaOrigen;
    private javax.swing.JLabel jLabelTiposArchivo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelConfiguracion;
    private javax.swing.JPanel jPanelOtrasOpciones;
    private javax.swing.JProgressBar jProgressBarFicherosCopiados;
    // End of variables declaration//GEN-END:variables

}
