/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.GUI;

import Vista.GUI.TableModel.FicheroTableModel;
import Vista.Logica.LogicaFichero;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gonzalo
 */
public class TablaFicheros extends javax.swing.JDialog {

    /**
     * Creates new form TablaFicheros
     */
    public TablaFicheros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTableFicheros.setModel(new FicheroTableModel(LogicaFichero.getListaFicheros()));
        iniciarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFicheros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableFicheros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTableFicheros);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de ficheros copiados");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonCerrar, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarMouseClicked
        limpiarTabla();
        dispose();
    }//GEN-LAST:event_jButtonCerrarMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFicheros;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     */
    private void iniciarTabla() {
        FicheroTableModel ftm = new FicheroTableModel(LogicaFichero.getListaFicheros());
        jTableFicheros.setModel(ftm);
        //Para poder ordenar la tabla
        TableRowSorter<FicheroTableModel> sorter = new TableRowSorter<>(ftm);
        jTableFicheros.setRowSorter(sorter);
    }

    /**
     * 
     */
    private void limpiarTabla() {
        for (int i = 0; i < jTableFicheros.getRowCount(); i++) {
            FicheroTableModel ctm = (FicheroTableModel) jTableFicheros.getModel();
            ctm.deleteRow(i);
            i--;
        }
    }

}
